<a href="https://colab.research.google.com/github/bpkwee/TCR_reconstruction/blob/main/random_primers_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#primer assignment to TCRs
## first run this to initialize the functions that are used

In [ ]:
import numpy as np
from collections import defaultdict

def check_unique(board, row, column):
    # Get distinct values from row and column
    row_values = np.unique(board[row,:])
    col_values = np.unique(board[:,column])

    # Bring all into one list
    all_values = np.concatenate((row_values, col_values), axis=None)

    # Then take the unique values from all of them
    unique_values = np.unique(all_values)

    return unique_values


def fill_values(board, row, column, number, primer_list):
    # We're only interested in values not yet filled
    if board[row,column] == 0:

        # Check unique numbers in row, column, and sub cell
        existing_values = check_unique(board, row, column)

        # Get numbers from 1-9 that don't appear in unique numbers list
        if number in existing_values:
            return True
            
        else: 
          board[row,column] = number
          primer_list[number].append((row,column))
          return False

## sudoku!
##fill in desired number of TCRs and number of replicates
The rows and column indices are the primers, the numbers in this matrix are the tcrs.

In [ ]:
n_tcr = 72 # can be changed to whatever is desired
tcr_replicates = 5

### now run the script to get the optimal layout

In [ ]:
total_tcr = tcr_replicates * n_tcr
axis_len = int(np.ceil(np.sqrt(total_tcr)))
print('number of tcrs {0} \n tcr replicates {1} \n total number of tcrs {2} \n and the length of the axis of the grid {3} \n (double it for the required number of primers) \n'.format(n_tcr,tcr_replicates,total_tcr,axis_len))


tcr_1d = [i for m in range(tcr_replicates)  for i in range(1, n_tcr+1) ]

# Get grid of 0's to represent empty cells
board_zeroes = np.zeros(shape=(axis_len,axis_len), dtype=int)
board_play = board_zeroes.copy()
tcr_primer_list = defaultdict(list)

# until all TCRs are placed
for i in range(10):
    for row in range(axis_len):
        for column in range(axis_len):
            if len(tcr_1d) >= 1:
                fail = True
                while fail:
                    number = tcr_1d.pop()
                    fail = fill_values(board_play, row, column, number, tcr_primer_list)
                    if not fail:
                        break
                    tcr_1d.insert(0, number)
                    
            else:
                break

print(board_play)




number of tcdrs 72 
 tcr replicates 5 
 total number of tcrs 360 
 and the length of the axis of the grid 19 
 (double it for the required number of primers) 

[[72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54]
 [53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35]
 [34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16]
 [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1 72 71 70 69]
 [68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50]
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31]
 [30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]
 [11 10  9  8  7  6  5  4  3  2  1 72 71 70 69 68 67 66 65]
 [64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46]
 [45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27]
 [26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8]
 [ 7  6  5  4  3  2  1 72 71 70 69 68 67 66 65 64 63 62 61]
 [60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42]
 [41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23]


## Extract a list of TCRs and their corresponding coordinates on the grid:

####(The rows and columns are numbered from 0, if this feature needs to be changed to start at 1 *just let me know!*)

In [ ]:
for tcr, values in tcr_primer_list.items():
    print('TCR number: {0} has primers sets {1}'.format(tcr,values))

TCR number: 72 has primers sets [(0, 0), (3, 15), (7, 11), (11, 7), (15, 3)]
TCR number: 71 has primers sets [(0, 1), (3, 16), (7, 12), (11, 8), (15, 4)]
TCR number: 70 has primers sets [(0, 2), (3, 17), (7, 13), (11, 9), (15, 5)]
TCR number: 69 has primers sets [(0, 3), (3, 18), (7, 14), (11, 10), (15, 6)]
TCR number: 68 has primers sets [(0, 4), (4, 0), (7, 15), (11, 11), (15, 7)]
TCR number: 67 has primers sets [(0, 5), (4, 1), (7, 16), (11, 12), (15, 8)]
TCR number: 66 has primers sets [(0, 6), (4, 2), (7, 17), (11, 13), (15, 9)]
TCR number: 65 has primers sets [(0, 7), (4, 3), (7, 18), (11, 14), (15, 10)]
TCR number: 64 has primers sets [(0, 8), (4, 4), (8, 0), (11, 15), (15, 11)]
TCR number: 63 has primers sets [(0, 9), (4, 5), (8, 1), (11, 16), (15, 12)]
TCR number: 62 has primers sets [(0, 10), (4, 6), (8, 2), (11, 17), (15, 13)]
TCR number: 61 has primers sets [(0, 11), (4, 7), (8, 3), (11, 18), (15, 14)]
TCR number: 60 has primers sets [(0, 12), (4, 8), (8, 4), (12, 0), (15, 

#  OLD APPROACH below!

In [ ]:
# import numpy as np
#
# tcr_replicates = 5
# n_tcr = 10 # can be changed to whatever is desired
# total_tcr = tcr_replicates * n_tcr
# axis_len = int(np.ceil(np.sqrt(total_tcr)))
#
# print('n_tcr%axis_len = {}'.format(n_tcr%axis_len))
#
# # if total tcr can be divided by axis length, we want to add 1 to the axis length
# modulo_check = [i for i in range(0,tcr_replicates,2)]
# if n_tcr%axis_len in modulo_check:
#     axis_len +=1
#
# n_primers = axis_len*2
#
# print('{0} primers ({2} axis len) needed for total {1} tcrs'.format(n_primers, total_tcr, axis_len))
#
# tcr_1d = np.array([i for j in range(tcr_replicates)  for i in range(1, n_tcr+1) ])
# print(len(tcr_1d))
# padding = np.zeros((axis_len*axis_len- len(tcr_1d)), dtype = int)
# print(len(padding))
# tcr_1d = np.append(tcr_1d,padding)
# print(len(tcr_1d))
# tcr_2d = tcr_1d.reshape(axis_len,axis_len)
# tcr_2d



In [ ]:
# import numpy as np
#
# tcr_replicates = 5
# n_tcrs = [i for i in range(9,40) ]# can be changed to whatever is desired
# for n_tcr in n_tcrs:
#     total_tcr = tcr_replicates * n_tcr
#     axis_len = int(np.ceil(np.sqrt(total_tcr)))
#
#
#     print('n_tcr%axis_len = {}'.format(n_tcr%axis_len))
#
#     # if total tcr can be divided by axis length, we want to add 1 to the axis length
#     modulo_check = [i for i in range(0,tcr_replicates,2)]
#     while n_tcr%axis_len in modulo_check:
#         axis_len +=1
#
#     print('n_tcr%axis_len = {}'.format(n_tcr%axis_len))
#     n_primers = axis_len*2
#
#     print('{0} primers ({2} axis len) needed for total {1} tcrs'.format(n_primers, total_tcr, axis_len))
#
#     tcr_1d = np.array([i for j in range(tcr_replicates)  for i in range(1, n_tcr+1) ])
#     print(len(tcr_1d))
#     padding = np.zeros((axis_len*axis_len- len(tcr_1d)), dtype = int)
#     print(len(padding))
#     tcr_1d = np.append(tcr_1d,padding)
#     print(len(tcr_1d))
#     tcr_2d = tcr_1d.reshape(axis_len,axis_len)
#     print(tcr_2d)



