In [1]:
import numpy as np
def check_unique(board, row, column):
    # Get distinct values from row and column
    row_values = np.unique(board[row,:])
    col_values = np.unique(board[:,column])

    # Bring all into one list
    all_values = np.concatenate((row_values, col_values), axis=None)

    # Then take the unique values from all of them
    unique_values = np.unique(all_values)

    return unique_values


def fill_values(board, row, column, number):
    # We're only interested in values not yet filled
    if board[row,column] == 0:

        # Check unique numbers in row, column, and sub cell
        existing_values = check_unique(board, row, column)

        # Get numbers from 1-9 that don't appear in unique numbers list
        if number in existing_values:
            number = 0

        board[row,column] = number

# new approach: sudoku!
fill in desired number of TCRs and number of replicates

In [10]:
n_tcr = 14 # can be changed to whatever is desired
tcr_replicates = 5

### now run the script to get the optimal layout

In [18]:
total_tcr = tcr_replicates * n_tcr
axis_len = int(np.ceil(np.sqrt(total_tcr)))
print(n_tcr,tcr_replicates,total_tcr,axis_len)


tcr_1d = [i for m in range(tcr_replicates)  for i in range(1, n_tcr+1) ]

# Get grid of 0's to represent empty cells
board_zeroes = np.zeros(shape=(axis_len,axis_len), dtype=int)
board_play = board_zeroes.copy()

# until all TCRs are placed
for i in range(10):
    for row in range(axis_len):
        for column in range(axis_len):
            if len(tcr_1d) > 1:
                number = tcr_1d.pop()
                fill_values(board_play, row, column, number)
            else:
                break

print(board_play)


14 5 70 9
[[14 13 12 11 10  9  8  7  6]
 [ 5  4  3  2  1 14 13 12 11]
 [10  9  8  7  6  5  4  3  2]
 [ 1 14 13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1 14 13 12]
 [11 10  9  8  7  6  5  4  3]
 [ 2  1 14 13 12 11 10  9  8]
 [ 7  6  5  4  3  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


#  OLD APPROACH below!

In [ ]:
# import numpy as np
#
# tcr_replicates = 5
# n_tcr = 10 # can be changed to whatever is desired
# total_tcr = tcr_replicates * n_tcr
# axis_len = int(np.ceil(np.sqrt(total_tcr)))
#
# print('n_tcr%axis_len = {}'.format(n_tcr%axis_len))
#
# # if total tcr can be divided by axis length, we want to add 1 to the axis length
# modulo_check = [i for i in range(0,tcr_replicates,2)]
# if n_tcr%axis_len in modulo_check:
#     axis_len +=1
#
# n_primers = axis_len*2
#
# print('{0} primers ({2} axis len) needed for total {1} tcrs'.format(n_primers, total_tcr, axis_len))
#
# tcr_1d = np.array([i for j in range(tcr_replicates)  for i in range(1, n_tcr+1) ])
# print(len(tcr_1d))
# padding = np.zeros((axis_len*axis_len- len(tcr_1d)), dtype = int)
# print(len(padding))
# tcr_1d = np.append(tcr_1d,padding)
# print(len(tcr_1d))
# tcr_2d = tcr_1d.reshape(axis_len,axis_len)
# tcr_2d



In [ ]:
# import numpy as np
#
# tcr_replicates = 5
# n_tcrs = [i for i in range(9,40) ]# can be changed to whatever is desired
# for n_tcr in n_tcrs:
#     total_tcr = tcr_replicates * n_tcr
#     axis_len = int(np.ceil(np.sqrt(total_tcr)))
#
#
#     print('n_tcr%axis_len = {}'.format(n_tcr%axis_len))
#
#     # if total tcr can be divided by axis length, we want to add 1 to the axis length
#     modulo_check = [i for i in range(0,tcr_replicates,2)]
#     while n_tcr%axis_len in modulo_check:
#         axis_len +=1
#
#     print('n_tcr%axis_len = {}'.format(n_tcr%axis_len))
#     n_primers = axis_len*2
#
#     print('{0} primers ({2} axis len) needed for total {1} tcrs'.format(n_primers, total_tcr, axis_len))
#
#     tcr_1d = np.array([i for j in range(tcr_replicates)  for i in range(1, n_tcr+1) ])
#     print(len(tcr_1d))
#     padding = np.zeros((axis_len*axis_len- len(tcr_1d)), dtype = int)
#     print(len(padding))
#     tcr_1d = np.append(tcr_1d,padding)
#     print(len(tcr_1d))
#     tcr_2d = tcr_1d.reshape(axis_len,axis_len)
#     print(tcr_2d)



